sequenceDiagram
    autonumber
    participant C as Client
    participant S as Server

    C->>S: GET /parameters
    S-->>C: 200 { P, G }

    Note over C: Derive x = derive(password, salt) mod Q<br/><br/> Pick random r in [1, Q-1] <BR/><br/>Compute T = G^r mod P

    C->>S: POST /login/commit { client_id, T }
        Note over S: Compute challenge <br/> c = H(peer_addr, UA, session_id, client_id, T) in [1, Q-1] <br/><br/>Generate session_id 
    S-->>C: 200 { session_id, challenge_c }

    Note over C: Compute s = (r + c * x) mod Q

    C->>S: POST /login/verify  { solution_s } <br/> X-Auth-Session: session_id 
    Note over S: Verify G^s == T * y^c (mod P)
    S-->>C: 200 { JWT }