erDiagram
	direction TB
	USER {
		int id PK ""  
		string client_id UK ""  
		bytes secret_y  ""  
		datetime created_at  ""  
	}


	DATA {
		int id PK ""  
		int client_id UK ""  
		string color  ""  
	}

	AUTH_TOKEN {
		int id PK ""  
		int user_id FK ""  
		string token UK ""  
		datetime created_at  ""  
	}
	OAUTH_CREDENTIAL {
		int id PK ""  
		string impl  ""  
		string client_id  ""  
		string pw_hash  ""  
	}

	style USER :stroke-width:2px,stroke-dasharray: 0